const express = require("express");
const controller = require("../controllers/share.controller");
const auth = require("../middleware/auth.middleware");
const router = express.Router();
router.get("/", auth, controller.listShareLinks);
router.post("/", auth, controller.createShareLink);
router.delete("/:token", auth, controller.revokeShareLink);
router.post("/:token/revoke", auth, controller.revokeShareLink);
router.get("/:token", controller.accessSharedFile);
router.post("/:token/preview", controller.streamPreview);
router.post("/:token/download", controller.downloadSharedFile);
router.post("/:token/access", controller.downloadSharedFile);
module.exports = router;
